global:
  resolve_timeout: 5m

route:
  receiver: 'discord-notifications'

receivers:
  - name: 'discord-notifications'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1370020546087096490/byci_zUP1eR6W-Z3OwBVXudH-equuJEodLCU7dbs460G_faqBVij4eOuPpZl5C_spN4'
        send_resolved: true
